apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php
          image: php:8.2-cli
          command: ["php", "-S", "0.0.0.0:8080", "-t", "/app"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          hostPath:
            path: /data/php
            type: Directory